/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsuldeminas.view;

import br.edu.ifsuldeminas.controller.ControllerCliente;

/**
 *
 * @author Marcos
 */
public class ViewMain extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    ViewRegister viewRegister = new ViewRegister();
    ControllerCliente controllerRegister = new ControllerCliente();

    public ViewMain() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mbMenu = new javax.swing.JMenuBar();
        jmCustomer = new javax.swing.JMenu();
        jmiRegister = new javax.swing.JMenuItem();
        jmiList = new javax.swing.JMenuItem();
        jmReport = new javax.swing.JMenu();
        jmiReport = new javax.swing.JMenuItem();
        jmAbout = new javax.swing.JMenu();
        jmExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu principal");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsuldeminas/imagens/CRUD.png"))); // NOI18N

        jmCustomer.setText("Clientes");

        jmiRegister.setText("Cadastro");
        jmiRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmiRegisterMouseClicked(evt);
            }
        });
        jmiRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegisterActionPerformed(evt);
            }
        });
        jmCustomer.add(jmiRegister);

        jmiList.setText("Listar");
        jmiList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmiListMouseClicked(evt);
            }
        });
        jmiList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListActionPerformed(evt);
            }
        });
        jmCustomer.add(jmiList);

        mbMenu.add(jmCustomer);

        jmReport.setText("Relatório");

        jmiReport.setText("Gerar relatório");
        jmReport.add(jmiReport);

        mbMenu.add(jmReport);

        jmAbout.setText("Sobre");
        jmAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAboutMouseClicked(evt);
            }
        });
        jmAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAboutActionPerformed(evt);
            }
        });
        mbMenu.add(jmAbout);

        jmExit.setText("Sair");
        jmExit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jmExit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jmExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmExitMouseClicked(evt);
            }
        });
        jmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmExitActionPerformed(evt);
            }
        });
        mbMenu.add(jmExit);

        setJMenuBar(mbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmExitActionPerformed

    }//GEN-LAST:event_jmExitActionPerformed

    private void jmExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_jmExitMouseClicked

    private void jmiRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegisterActionPerformed

        viewRegister.setVisible(true);
    }//GEN-LAST:event_jmiRegisterActionPerformed

    private void jmAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmAboutActionPerformed

    private void jmAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAboutMouseClicked
        ViewAbout viewAbout = new ViewAbout();
        viewAbout.setVisible(true);

    }//GEN-LAST:event_jmAboutMouseClicked

    private void jmiRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiRegisterMouseClicked

    }//GEN-LAST:event_jmiRegisterMouseClicked

    private void jmiListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiListMouseClicked

    private void jmiListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListActionPerformed
        ViewCustomerList viewCustomerList = new ViewCustomerList();
        viewCustomerList.setVisible(true);
    }//GEN-LAST:event_jmiListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jmAbout;
    private javax.swing.JMenu jmCustomer;
    private javax.swing.JMenu jmExit;
    private javax.swing.JMenu jmReport;
    private javax.swing.JMenuItem jmiList;
    private javax.swing.JMenuItem jmiRegister;
    private javax.swing.JMenuItem jmiReport;
    private javax.swing.JMenuBar mbMenu;
    // End of variables declaration//GEN-END:variables
}
